ATLAS___MODULE_ID__="__MODULE_ID__"
ATLAS___MODULE_NAME__="__MODULE_NAME__"
ATLAS_MODULE_VERSION="0.1.0"
ATLAS___MODULE_DESCRIPTION__="__MODULE_DESCRIPTION__"
ATLAS_MODULE_COMPOSE_FILE="docker-compose.yml"
ATLAS_MODULE_ENABLED_DEFAULT="false"
